# Indigo Hartsell
# 2024-09-01

# This script is designed to be used with my spotify network visualization
# It takes genres from a csv output by the network visualization and attempts to resolve them to a category

import pandas as pd
import json

def chunk_missing_genres():
    # Load the data
    data = pd.read_csv('out/entries_without_genre.csv')

    # 'Genre' column contains a python list of genres for each track. Extract them into a single list containing only unique values
    genres = []
    for i in range(len(data)):
        # Check if the genre is a list or a float
        if type(data['Genres'][i]) is str:
            # Parse the string into a list
            genre_list = data['Genres'][i].strip('[]').replace("'", "").split(',')
            # Add each genre to the list
            for genre in genre_list:
                if genre not in genres:
                    genres.append(genre)

    # Print list in 50-genre chunks so I can manually categorize them
    for i in range(0, len(genres), 50):
        print(genres[i:i+50])
        print()

def create_mapping():
    genre_to_category = {
        'east coast hip hop': 'Miscellaneous',
        'gangster rap': 'Miscellaneous',
        'hip hop': 'Miscellaneous',
        'pop rap': 'Miscellaneous',
        'rap': 'Miscellaneous',
        'canadian indie rock': 'Pop & Indie',
        'pov: indie': 'Pop & Indie',
        'vancouver indie': 'Pop & Indie',
        'asheville indie': 'Pop & Indie',
        'bubblegrunge': 'Pop & Indie',
        'countrygaze': 'Pop & Indie',
        'slacker rock': 'Pop & Indie',
        'american post-punk': 'Alternative & Experimental',
        'indie punk': 'Alternative & Experimental',
        'hopebeat': 'Pop & Indie',
        'indie poptimism': 'Pop & Indie',
        'metropopolis': 'Pop & Indie',
        'alternative metal': 'Rock & Metal',
        'modern rock': 'Rock & Metal',
        'pop punk': 'Rock & Metal',
        'punk': 'Rock & Metal',
        'rock': 'Rock & Metal',
        'socal pop punk': 'Rock & Metal',
        'electropop': 'Electronic & Dance',
        'etherpop': 'Electronic & Dance',
        'pop': 'Pop & Indie',
        'dreamo': 'Pop & Indie',
        'grungegaze': 'Rock & Metal',
        'modern alternative rock': 'Rock & Metal',
        'post-grunge': 'Rock & Metal',
        'indie pop': 'Pop & Indie',
        'stomp and holler': 'Pop & Indie',
        'psychedelic folk rock': 'Folk & Country',
        'crank wave': 'Alternative & Experimental',
        'indie rock': 'Pop & Indie',
        'art pop': 'Pop & Indie',
        'candy pop': 'Pop & Indie',
        'uk pop': 'Pop & Indie',
        'escape room': 'Alternative & Experimental',
        'acoustic punk': 'Alternative & Experimental',
        'folk punk': 'Folk & Country',
        'alternative rock': 'Rock & Metal',
        'modern power pop': 'Pop & Indie',
        'permanent wave': 'Pop & Indie',
        'la pop': 'Pop & Indie',
        'opm': 'World & Regional',
        'hip pop': 'Miscellaneous',
        'boy band': 'Pop & Indie',
        'dance pop': 'Electronic & Dance',
        'dance rock': 'Electronic & Dance',
        'pop rock': 'Rock & Metal',
        'la indie': 'Pop & Indie',
        'anti-folk': 'Folk & Country',
        'piano rock': 'Rock & Metal',
        'colombian pop': 'World & Regional',
        'chamber pop': 'Pop & Indie',
        'indietronica': 'Electronic & Dance',
        'washington indie': 'Pop & Indie',
        'irish rock': 'Rock & Metal',
        'utah indie': 'Pop & Indie',
        'gauze pop': 'Pop & Indie',
        'shiver pop': 'Pop & Indie',
        'modern dream pop': 'Pop & Indie',
        'acoustic rock': 'Rock & Metal',
        'grunge': 'Rock & Metal',
        'nu metal': 'Rock & Metal',
        'zoomergaze': 'Alternative & Experimental',
        'alt z': 'Alternative & Experimental',
        'dark pop': 'Pop & Indie',
        'zxc': 'Miscellaneous',
        'prog metal': 'Rock & Metal',
        'indie garage rock': 'Rock & Metal',
        'canadian indie': 'Pop & Indie',
        'canadian rock': 'Rock & Metal',
        'neo-synthpop': 'Electronic & Dance',
        'small room': 'Miscellaneous',
        'nyc indie rock': 'Rock & Metal',
        'american primitive': 'Folk & Country',
        'experimental guitar': 'Alternative & Experimental',
        'pastoral': 'Classical & Traditional',
        'electro-pop francais': 'Electronic & Dance',
        'shimmer pop': 'Pop & Indie',
        'nz pop': 'Pop & Indie',
        'atlanta indie': 'Pop & Indie',
        'new jersey indie': 'Pop & Indie',
        'nashville indie': 'Pop & Indie',
        'vapor soul': 'Pop & Indie',
        'portland indie': 'Pop & Indie',
        'british alternative rock': 'Rock & Metal',
        'emo': 'Alternative & Experimental',
        'electropowerpop': 'Electronic & Dance',
        'neon pop punk': 'Pop & Indie',
        'nintendocore': 'Alternative & Experimental',
        'screamo': 'Rock & Metal',
        'trancecore': 'Electronic & Dance',
        'canadian punk': 'Rock & Metal',
        'skate punk': 'Rock & Metal',
        'rap rock': 'Rock & Metal',
        'reggae fusion': 'World & Regional',
        'ska mexicano': 'World & Regional',
        'ska punk': 'Rock & Metal',
        'hard rock': 'Rock & Metal',
        'supergroup': 'Miscellaneous',
        'modern ska punk': 'Rock & Metal',
        'ska': 'World & Regional',
        'rap metal': 'Rock & Metal',
        'hardcore hip hop': 'Miscellaneous',
        'american metalcore': 'Rock & Metal',
        'columbus ohio indie': 'Pop & Indie',
        'bronx hip hop': 'Miscellaneous',
        'olympia wa indie': 'Pop & Indie',
        'funk metal': 'Rock & Metal',
        'power pop': 'Pop & Indie',
        'reggae rock': 'World & Regional',
        'funk rock': 'Rock & Metal',
        'hardcore punk': 'Rock & Metal',
        'alternative emo': 'Alternative & Experimental',
        'anthem emo': 'Alternative & Experimental',
        'atlanta punk': 'Rock & Metal',
        'pop emo': 'Pop & Indie',
        'post-hardcore': 'Rock & Metal',
        'seattle hip hop': 'Miscellaneous',
        'instrumental hip hop': 'Miscellaneous',
        'jazz boom bap': 'Jazz & Blues',
        'turntablism': 'Electronic & Dance',
        'modern blues': 'Jazz & Blues',
        'neo soul': 'Jazz & Blues',
        'soul': 'Jazz & Blues',
        'canadian contemporary r&b': 'Pop & Indie',
        'canadian pop': 'Pop & Indie',
        'electro': 'Electronic & Dance',
        'filter house': 'Electronic & Dance',
        'industrial metal': 'Rock & Metal',
        'hyperpop': 'Pop & Indie',
        'pink noise': 'Alternative & Experimental',
        'proto-hyperpop': 'Alternative & Experimental',
        'estonian pop': 'World & Regional',
        'christian rock': 'Rock & Metal',
        'diy emo': 'Alternative & Experimental',
        'dream pop': 'Pop & Indie',
        'hyper-rock': 'Rock & Metal',
        'pixie': 'Alternative & Experimental',
        'atmospheric dnb': 'Electronic & Dance',
        'chill breakcore': 'Electronic & Dance',
        'glitchbreak': 'Electronic & Dance',
        'glitchcore': 'Electronic & Dance',
        'japanese electropop': 'Electronic & Dance',
        'digital hardcore': 'Electronic & Dance',
        'bubblegum bass': 'Pop & Indie',
        'canadian metal': 'Rock & Metal',
        'glam metal': 'Rock & Metal',
        'minneapolis indie': 'Pop & Indie',
        'boston rock': 'Rock & Metal',
        'dariacore': 'Electronic & Dance',
        'indie game soundtrack': 'Soundtracks & Themes',
        'sacramento indie': 'Pop & Indie',
        'cleveland indie': 'Pop & Indie',
        'alternative r&b': 'Alternative & Experimental',
        'bc underground hip hop': 'Miscellaneous',
        'canadian hip hop': 'Miscellaneous',
        'canadian trap': 'Miscellaneous',
        'trap queen': 'Miscellaneous',
        'brooklyn indie': 'Pop & Indie',
        'abstract hip hop': 'Alternative & Experimental',
        'outer hip hop': 'Alternative & Experimental',
        'elephant 6': 'Pop & Indie',
        'lo-fi': 'Alternative & Experimental',
        'noise pop': 'Alternative & Experimental',
        'furry': 'Miscellaneous',
        'hypnagogic pop': 'Alternative & Experimental',
        'vaporwave': 'Electronic & Dance',
        'irish singer-songwriter': 'Folk & Country',
        'experimental rock': 'Alternative & Experimental',
        'noise rock': 'Alternative & Experimental',
        'psychedelic punk': 'Alternative & Experimental',
        'philly indie': 'Pop & Indie',
        'afrofuturism': 'Alternative & Experimental',
        'spacegrunge': 'Alternative & Experimental',
        'christian alternative rock': 'Alternative & Experimental',
        '5th wave emo': 'Alternative & Experimental',
        'midwest emo': 'Alternative & Experimental',
        'queercore': 'Alternative & Experimental',
        'albany ny indie': 'Pop & Indie',
        'boston punk': 'Alternative & Experimental',
        'industrial hip hop': 'Alternative & Experimental',
        'political hip hop': 'Alternative & Experimental',
        'kent indie': 'Pop & Indie',
        'canadian pop punk': 'Pop & Indie',
        'boston indie': 'Pop & Indie',
        'maine indie': 'Pop & Indie',
        'neo mellow': 'Pop & Indie',
        'texasgaze': 'Alternative & Experimental',
        'grave wave': 'Alternative & Experimental',
        'shoegaze': 'Alternative & Experimental',
        'gainesville indie': 'Pop & Indie',
        'orgcore': 'Alternative & Experimental',
        'experimental hip hop': 'Alternative & Experimental',
        'drumless hip hop': 'Alternative & Experimental',
        'alternative hip hop': 'Alternative & Experimental',
        'german pop': 'Pop & Indie',
        'new wave pop': 'Pop & Indie',
        'dance-punk': 'Electronic & Dance',
        'classic rock': 'Rock & Metal',
        'alternative dance': 'Electronic & Dance',
        'bitpop': 'Electronic & Dance',
        'new rave': 'Electronic & Dance',
        'uk pop punk': 'Pop & Indie',
        'classic soul': 'Miscellaneous',
        'funk': 'Miscellaneous',
        'quiet storm': 'Miscellaneous',
        'riot grrrl': 'Alternative & Experimental',
        'chicago indie': 'Pop & Indie',
        'chicago rap': 'Miscellaneous',
        'conscious hip hop': 'Miscellaneous',
        'southern hip hop': 'Miscellaneous',
        'art rock': 'Alternative & Experimental',
        'progressive metal': 'Rock & Metal',
        'progressive rock': 'Rock & Metal',
        'asbury park indie': 'Pop & Indie',
        'alternative pop': 'Pop & Indie',
        'lilith': 'Pop & Indie',
        'modern blues rock': 'Jazz & Blues',
        'modern hard rock': 'Rock & Metal',
        'chapel hill sound': 'Pop & Indie',
        'comic': 'Miscellaneous',
        'power-pop punk': 'Pop & Indie',
        'ramonescore': 'Rock & Metal',
        'brighton indie': 'Pop & Indie',
        'garage rock': 'Rock & Metal',
        'ok indie': 'Pop & Indie',
        'okc indie': 'Pop & Indie',
        'oakland indie': 'Pop & Indie',
        'texas pop punk': 'Pop & Indie',
        'modern hardcore': 'Rock & Metal',
        'canadian electropop': 'Electronic & Dance',
        'album rock': 'Rock & Metal',
        'birmingham metal': 'Rock & Metal',
        'metal': 'Rock & Metal',
        'golden age hip hop': 'Miscellaneous',
        'old school hip hop': 'Miscellaneous',
        'transpop': 'Electronic & Dance',
        'new england emo': 'Alternative & Experimental',
        'modern indie pop': 'Pop & Indie',
        'twee pop': 'Pop & Indie',
        'slayer': 'Rock & Metal',
        'comedy rock': 'Miscellaneous',
        'comic metal': 'Miscellaneous',
        'parody': 'Miscellaneous',
        'punk blues': 'Jazz & Blues',
        'nwobhm': 'Rock & Metal',
        'kc indie': 'Pop & Indie',
        'britpop': 'Pop & Indie',
        'madchester': 'Pop & Indie',
        'texas punk': 'Alternative & Experimental',
        'australian psych': 'Pop & Indie',
        'double drumming': 'Miscellaneous',
        'microtonal': 'Miscellaneous',
        'neo-psychedelic': 'Pop & Indie',
        'indie soul': 'Pop & Indie',
        'kiwi rock': 'Pop & Indie',
        'portland hip hop': 'Miscellaneous',
        'psychedelic pop': 'Pop & Indie',
        'tulsa indie': 'Pop & Indie',
        'weirdcore': 'Alternative & Experimental',
        'synthpop': 'Pop & Indie',
        'london indie': 'Pop & Indie',
        'post-teen pop': 'Pop & Indie',
        'detroit hip hop': 'Miscellaneous',
        'russian indie': 'Pop & Indie',
        'russian punk': 'Alternative & Experimental',
        'electro house': 'Electronic & Dance',
        'fidget house': 'Electronic & Dance',
        'german dance': 'Electronic & Dance',
        'german techno': 'Electronic & Dance',
        'vegas indie': 'Pop & Indie',
        'nu disco': 'Electronic & Dance',
        'electronic rock': 'Electronic & Dance',
        'industrial rock': 'Rock & Metal',
        'british invasion': 'Rock & Metal',
        'phoenix indie': 'Pop & Indie',
        'jazz rap': 'Miscellaneous',
        'queens hip hop': 'Miscellaneous',
        'baroque pop': 'Pop & Indie',
        'melancholia': 'Miscellaneous',
        'scottish indie': 'Pop & Indie',
        'scottish rock': 'Rock & Metal',
        'singer-songwriter': 'Folk & Country',
        'alternative pop rock': 'Pop & Indie',
        'bedroom pop': 'Pop & Indie',
        'california hardcore': 'Alternative & Experimental',
        'crossover thrash': 'Rock & Metal',
        'old school thrash': 'Rock & Metal',
        'thrash metal': 'Rock & Metal',
        'new wave': 'Pop & Indie',
        'uk post-punk': 'Alternative & Experimental',
        'cowpunk': 'Alternative & Experimental',
        'athens indie': 'Pop & Indie',
        'new weird america': 'Alternative & Experimental',
        'lo-fi indie': 'Pop & Indie',
        'pennsylvania shoegaze': 'Pop & Indie',
        'barbadian pop': 'Pop & Indie',
        'urban contemporary': 'Pop & Indie',
        'charlottesville indie': 'Pop & Indie',
        'eugene indie': 'Pop & Indie',
        'oxford indie': 'Pop & Indie',
        'melodic hardcore': 'Rock & Metal',
        'progressive post-hardcore': 'Rock & Metal',
        'chamber psych': 'Alternative & Experimental',
        'experimental dub': 'Alternative & Experimental',
        'illbient': 'Alternative & Experimental',
        'spectra': 'Miscellaneous',
        'video game music': 'Soundtracks & Themes',
        'otacore': 'Soundtracks & Themes',
        'vgm instrumental': 'Soundtracks & Themes',
        'psychedelic rock': 'Rock & Metal',
        'symphonic rock': 'Rock & Metal',
        'indie pop rap': 'Pop & Indie',
        'pop dance': 'Electronic & Dance',
        'manitoba indie': 'Pop & Indie',
        'singer-songwriter pop': 'Folk & Country',
        'black punk': 'Rock & Metal',
        'glam punk': 'Rock & Metal',
        'chicago pop punk': 'Rock & Metal',
        'uk diy punk': 'Rock & Metal',
        'lgbtq+ hip hop': 'Pop & Indie',
        'long island punk': 'Rock & Metal',
        'portland punk': 'Rock & Metal',
        'australian alternative rock': 'Alternative & Experimental',
        'viral rap': 'Pop & Indie',
        'experimental r&b': 'Pop & Indie',
        'electra': 'Electronic & Dance',
        'r&b': 'Pop & Indie',
        'glam rock': 'Rock & Metal',
        'mellow gold': 'Miscellaneous',
        'brisbane indie': 'Pop & Indie',
        'dark trap': 'Pop & Indie',
        'lancaster pa indie': 'Pop & Indie',
        'pittsburgh indie': 'Pop & Indie',
        'lincoln ne indie': 'Pop & Indie',
        'hip-hop experimental': 'Pop & Indie',
        'ontario indie': 'Pop & Indie',
        'american shoegaze': 'Alternative & Experimental',
        'nu gaze': 'Alternative & Experimental',
        'meme rap': 'Miscellaneous',
        'instrumental rock': 'Rock & Metal',
        'denton tx indie': 'Pop & Indie',
        'gaming edm': 'Electronic & Dance',
        'finnish edm': 'Electronic & Dance',
        'country rock': 'Folk & Country',
        'folk': 'Folk & Country',
        'folk rock': 'Rock & Metal',
        'soft rock': 'Rock & Metal',
        'new romantic': 'Pop & Indie',
        'broadway': 'Soundtracks & Themes',
        'show tunes': 'Soundtracks & Themes',
        'movie tunes': 'Soundtracks & Themes',
        'australian hip hop': 'Miscellaneous',
        'k-pop': 'Pop & Indie',
        'k-rap': 'Pop & Indie',
        'korean r&b': 'Pop & Indie',
        'sped up': 'Electronic & Dance',
        'deconstructed club': 'Electronic & Dance',
        'fluxwork': 'Electronic & Dance',
        'grimewave': 'Electronic & Dance',
        'gothic alternative': 'Alternative & Experimental',
        'industrial pop': 'Alternative & Experimental',
        'doomgaze': 'Alternative & Experimental',
        'gaian doom': 'Alternative & Experimental',
        'idol rock': 'Rock & Metal',
        'j-metal': 'Rock & Metal',
        'kawaii metal': 'Rock & Metal',
        'manchester indie': 'Pop & Indie',
        'mathcore': 'Rock & Metal',
        'melodic metalcore': 'Rock & Metal',
        'metalcore': 'Rock & Metal',
        'progressive metalcore': 'Rock & Metal',
        'uk metalcore': 'Rock & Metal',
        'toronto indie': 'Pop & Indie',
        'west coast reggae': 'World & Regional',
        'buffalo ny indie': 'Pop & Indie',
        'connecticut indie': 'Pop & Indie',
        'indie rock italiano': 'Pop & Indie',
        'italian pop': 'Pop & Indie',
        'sleaze rock': 'Rock & Metal',
        'bass house': 'Electronic & Dance',
        'house': 'Electronic & Dance',
        'tech house': 'Electronic & Dance',
        'scream rap': 'Miscellaneous',
        'indie electropop': 'Pop & Indie',
        'modern alternative pop': 'Pop & Indie',
        'british indie rock': 'Pop & Indie',
        'social media pop': 'Pop & Indie',
        'australian electropop': 'Pop & Indie',
        'classic canadian rock': 'Rock & Metal',
        'canadian ccm': 'Miscellaneous',
        'christian punk': 'Miscellaneous',
        'oc indie': 'Pop & Indie',
        'kentucky indie': 'Pop & Indie',
        'kentucky roots': 'Folk & Country',
        'outlaw country': 'Folk & Country',
        'idaho indie': 'Pop & Indie',
        '2-step': 'Electronic & Dance',
        'uk funky': 'Electronic & Dance',
        'uk garage': 'Electronic & Dance',
        'uk alternative hip hop': 'Alternative & Experimental',
        'uk hip hop': 'Alternative & Experimental',
        'english indie rock': 'Pop & Indie',
        'trap': 'Electronic & Dance',
        'atl hip hop': 'Alternative & Experimental',
        'melodic rap': 'Alternative & Experimental',
        'afroswing': 'World & Regional',
        'london rap': 'Alternative & Experimental',
        'g funk': 'Alternative & Experimental',
        'west coast rap': 'Alternative & Experimental',
        'chicago house': 'Electronic & Dance',
        'classic house': 'Electronic & Dance',
        'chillwave': 'Electronic & Dance',
        'downtempo': 'Electronic & Dance',
        'electronica': 'Electronic & Dance',
        'gothenburg indie': 'Pop & Indie',
        'swedish electropop': 'Electronic & Dance',
        'swedish synthpop': 'Electronic & Dance',
        'trip hop': 'Electronic & Dance',
        'uk alternative pop': 'Pop & Indie',
        'stl indie': 'Pop & Indie',
        'pixel': 'Soundtracks & Themes',
        'math pop': 'Alternative & Experimental',
        'comedy rap': 'Miscellaneous',
        'djent': 'Rock & Metal',
        'instrumental math rock': 'Rock & Metal',
        'math rock': 'Rock & Metal',
        'fort worth indie': 'Pop & Indie',
        'japanese math rock': 'Rock & Metal',
        'japanese jazz fusion': 'Jazz & Blues',
        'japanese jazztronica': 'Jazz & Blues',
        'japanese post-rock': 'Rock & Metal',
        'swancore': 'Rock & Metal',
        'modern jazz trio': 'Jazz & Blues',
        'nyc pop': 'Pop & Indie',
        'comfy synth': 'Electronic & Dance',
        'indie psych-pop': 'Pop & Indie',
        'shimmer psych': 'Pop & Indie',
        'jazztronica': 'Jazz & Blues',
        'livetronica': 'Electronic & Dance',
        'slovenian electronic': 'Electronic & Dance',
        'progressive jazz fusion': 'Jazz & Blues',
        'kawaii future bass': 'Electronic & Dance',
        'korean indie rock': 'Pop & Indie',
        'baltimore indie': 'Pop & Indie',
        'dark cabaret': 'Alternative & Experimental',
        'steampunk': 'Alternative & Experimental',
        'cloud rap': 'Miscellaneous',
        'drain': 'Miscellaneous',
        'underground hip hop': 'Miscellaneous',
        'indie surf': 'Pop & Indie',
        'pittsburgh indie rock': 'Pop & Indie',
        'lo-fi emo': 'Pop & Indie',
        'german soundtrack': 'Soundtracks & Themes',
        'orchestral soundtrack': 'Soundtracks & Themes',
        'soundtrack': 'Soundtracks & Themes',
        'australian garage punk': 'Alternative & Experimental',
        'south carolina indie': 'Pop & Indie',
        'brostep': 'Electronic & Dance',
        'edm': 'Electronic & Dance',
        'electronic trap': 'Electronic & Dance',
        'future bass': 'Electronic & Dance',
        'complextro': 'Electronic & Dance',
        'breakbeat': 'Electronic & Dance',
        'deep dnb': 'Electronic & Dance',
        'drum and bass': 'Electronic & Dance',
        'dutch dnb': 'Electronic & Dance',
        'neurofunk': 'Electronic & Dance',
        'vapor twitch': 'Electronic & Dance',
        'abstract beats': 'Electronic & Dance',
        'indie jazz': 'Jazz & Blues',
        'chillhop': 'Electronic & Dance',
        'lo-fi beats': 'Electronic & Dance',
        'tempe indie': 'Pop & Indie',
        'modern folk rock': 'Folk & Country',
        'contemporary jazz': 'Jazz & Blues',
        'jazz': 'Jazz & Blues',
        'jazz saxophone': 'Jazz & Blues',
        'folk-pop': 'Folk & Country',
        'high vibe': 'Miscellaneous',
        'australian indie folk': 'Folk & Country',
        'australian reggae fusion': 'World & Regional',
        'corecore': 'Alternative & Experimental',
        'tucson indie': 'Pop & Indie',
        'celtic punk': 'World & Regional',
        'celtic rock': 'World & Regional',
        'brazilian progressive metal': 'Rock & Metal',
        'instrumental djent': 'Rock & Metal',
        'japanese guitar': 'Rock & Metal',
        'british math rock': 'Rock & Metal',
        'gypsy punk': 'Alternative & Experimental',
        'canadian singer-songwriter': 'Folk & Country',
        'hands up': 'Electronic & Dance',
        'nightcore': 'Electronic & Dance',
        'bay area indie': 'Pop & Indie',
        'dutch indie': 'Pop & Indie',
        'heartland rock': 'Rock & Metal',
        'new brunswick indie': 'Pop & Indie',
        'slowcore': 'Pop & Indie',
        'ambient worship': 'Miscellaneous',
        'crack rock steady': 'Rock & Metal',
        'shibuya-kei': 'World & Regional',
        'picopop': 'World & Regional',
        'j-ambient': 'World & Regional',
        'nu jazz': 'Jazz & Blues',
        'australian metal': 'Rock & Metal',
        'lo-fi rap': 'Miscellaneous',
        'milwaukee indie': 'Pop & Indie',
        'dark synthpop': 'Electronic & Dance',
        'witch house': 'Electronic & Dance',
        'anime': 'Soundtracks & Themes',
        'experimental black metal': 'Alternative & Experimental',
        'nyc metal': 'Rock & Metal',
        'technical black metal': 'Rock & Metal',
        'totalism': 'Miscellaneous',
        'usbm': 'Rock & Metal',
        'russian witch house': 'Electronic & Dance',
        'new jersey hardcore': 'Rock & Metal',
        'nerdcore': 'Miscellaneous',
        'dancehall': 'World & Regional',
        'jamaican hip hop': 'World & Regional',
        'traphall': 'World & Regional',
        'jam band': 'Miscellaneous',
        'charlotte nc indie': 'Pop & Indie',
        'country rap': 'Folk & Country',
        'instrumental post-rock': 'Rock & Metal',
        'anarcho-punk': 'Alternative & Experimental',
        'kirtan': 'World & Regional',
        'world fusion': 'World & Regional',
        'laboratorio': 'Alternative & Experimental',
        'new americana': 'Folk & Country',
        'progressive bluegrass': 'Folk & Country',
        'washboard': 'Folk & Country',
        'shamanic': 'World & Regional',
        'viral trap': 'Electronic & Dance',
        'virginia hip hop': 'Miscellaneous',
        'nordic soundtrack': 'Soundtracks & Themes',
        'jazz funk': 'Jazz & Blues',
        'jazz guitar': 'Jazz & Blues',
        'smooth jazz': 'Jazz & Blues',
        'soul jazz': 'Jazz & Blues',
        'yacht rock': 'Rock & Metal',
        'canterbury scene': 'Rock & Metal',
        'jazz rock': 'Rock & Metal',
        'italian progressive rock': 'Rock & Metal',
        'dutch prog': 'Rock & Metal',
        'flute rock': 'Rock & Metal',
        'nederpop': 'Pop & Indie',
        'bergen indie': 'Pop & Indie',
        'jazz metal': 'Rock & Metal',
        'instrumental progressive metal': 'Rock & Metal',
        'solo wave': 'Miscellaneous',
        'welsh indie': 'Pop & Indie',
        'welsh rock': 'Rock & Metal',
        'shred': 'Rock & Metal',
        'sillycore': 'Miscellaneous',
        'j-pop': 'World & Regional',
        'j-poprock': 'World & Regional',
        'j-rock': 'World & Regional',
        'dubstep': 'Electronic & Dance',
        'melodic dubstep': 'Electronic & Dance',
        'aussietronica': 'Electronic & Dance',
        'pop edm': 'Electronic & Dance',
        'norwegian pop': 'Pop & Indie',
        'indie rockism': 'Pop & Indie',
        'uk americana': 'Folk & Country',
        'new french touch': 'Electronic & Dance',
        'christian lo-fi': 'Miscellaneous',
        'anime lo-fi': 'Miscellaneous',
        'lo-fi study': 'Miscellaneous',
        'boom bap': 'Miscellaneous',
        'lo-fi jazzhop': 'Electronic & Dance',
        'dancefloor dnb': 'Electronic & Dance',
        'uk dance': 'Electronic & Dance',
        'deep liquid': 'Electronic & Dance',
        'stateside dnb': 'Electronic & Dance',
        'birmingham indie': 'Pop & Indie',
        'nyc rap': 'Miscellaneous',
        'dfw rap': 'Miscellaneous',
        'reggaeton': 'World & Regional',
        'reggaeton flow': 'World & Regional',
        'trap boricua': 'World & Regional',
        'trap latino': 'World & Regional',
        'urbano latino': 'World & Regional',
        'zimdancehall': 'World & Regional',
        'modern country pop': 'Folk & Country',
        'cincinnati rap': 'Miscellaneous',
        'miami hip hop': 'Miscellaneous',
        'pop r&b': 'Pop & Indie',
        'new jersey underground rap': 'Miscellaneous',
        'dmv rap': 'Miscellaneous',
        'new orleans rap': 'Miscellaneous',
        'trap soul': 'Miscellaneous',
        'emo rap': 'Miscellaneous',
        'drill': 'Miscellaneous',
        'indie hip hop': 'Miscellaneous',
        'epicore': 'Soundtracks & Themes',
        'p funk': 'Miscellaneous',
        'japanese chillhop': 'Electronic & Dance',
        'south african hip hop': 'World & Regional',
        'spiritual hip hop': 'Miscellaneous',
        'uk contemporary r&b': 'Pop & Indie',
        'cali rap': 'Miscellaneous',
        'afro soul': 'World & Regional',
        'gqom': 'World & Regional',
        'south african pop': 'World & Regional',
        'sacramento hip hop': 'Miscellaneous',
        'slap house': 'Electronic & Dance',
        'afrobeats': 'World & Regional',
        'nigerian hip hop': 'World & Regional',
        'nigerian pop': 'World & Regional',
        'chinese r&b': 'World & Regional',
        'viral pop': 'Pop & Indie',
        'saskatchewan indie': 'Pop & Indie',
        'hardcore breaks': 'Electronic & Dance',
        'bass trap': 'Electronic & Dance',
        'jamtronica': 'Electronic & Dance',
        'antiviral pop': 'Pop & Indie',
        'pittsburgh rap': 'Miscellaneous',
        'dutch house': 'Electronic & Dance',
        'melbourne bounce': 'Electronic & Dance',
        'progressive electro house': 'Electronic & Dance',
        'sky room': 'Electronic & Dance',
        'waiata mo tamariki': 'World & Regional',
        'karaoke': 'Miscellaneous',
        'chillstep': 'Electronic & Dance',
        'filthstep': 'Electronic & Dance',
        'meme': 'Miscellaneous',
        'rap conciencia': 'Miscellaneous',
        'stomp pop': 'Pop & Indie',
        'oakland hip hop': 'Miscellaneous',
        'progressive house': 'Electronic & Dance',
        'stutter house': 'Electronic & Dance',
        'moombahton': 'Electronic & Dance',
        'danish pop': 'World & Regional',
        'harlem hip hop': 'Miscellaneous',
        'new jack swing': 'Miscellaneous',
        'vocal house': 'Electronic & Dance',
        'canadian electronic': 'Electronic & Dance',
        'bow pop': 'Pop & Indie',
        'pop violin': 'Pop & Indie',
        'easycore': 'Rock & Metal',
        'cincinnati indie': 'Pop & Indie',
        'contemporary r&b': 'Pop & Indie',
        'south carolina hip hop': 'Miscellaneous',
        'dark r&b': 'Pop & Indie',
        'merseybeat': 'Rock & Metal',
        'banjo': 'Folk & Country',
        'bluegrass': 'Folk & Country',
        'indie folk': 'Folk & Country',
        'mandolin': 'Folk & Country',
        'german post-hardcore': 'Rock & Metal',
        'canadian post-hardcore': 'Rock & Metal',
        'gen z singer-songwriter': 'Pop & Indie',
        'miami indie': 'Pop & Indie',
        'punk cover': 'Rock & Metal',
        'east anglia indie': 'Pop & Indie',
        'post-screamo': 'Rock & Metal',
        'deep talent show': 'Miscellaneous',
        'contemporary country': 'Folk & Country',
        'alternative roots rock': 'Rock & Metal',
        'slc indie': 'Pop & Indie',
        'nu-metalcore': 'Rock & Metal',
        'classic oklahoma country': 'Folk & Country',
        'garage rock revival': 'Rock & Metal',
        'indiecoustica': 'Pop & Indie',
        'kingston on indie': 'Pop & Indie',
        'socal indie': 'Pop & Indie',
        'french indietronica': 'Electronic & Dance',
        'aussie emo': 'Pop & Indie',
        'warrington indie': 'Pop & Indie',
        'country road': 'Folk & Country',
        'modern country rock': 'Folk & Country',
        'kelowna bc indie': 'Pop & Indie',
        'vancouver punk': 'Rock & Metal',
        'knoxville indie': 'Pop & Indie',
        'american folk revival': 'Folk & Country',
        'old-time': 'Folk & Country',
        'traditional folk': 'Folk & Country',
        'protest folk': 'Folk & Country',
        'traditional blues': 'Jazz & Blues',
        'thall': 'Rock & Metal',
        'worcester ma indie': 'Pop & Indie',
        'deep underground hip hop': 'Miscellaneous',
        'louisville indie': 'Pop & Indie',
        'swedish alternative rock': 'Rock & Metal',
        'canadian garage rock': 'Rock & Metal',
        'queer country': 'Folk & Country',
        'strut': 'Miscellaneous',
        'london on indie': 'Pop & Indie',
        'edmonton indie': 'Pop & Indie',
        'arkansas indie': 'Pop & Indie',
        'australian rock': 'Rock & Metal',
        'minnesota hip hop': 'Miscellaneous',
        'indonesian hip hop': 'World & Regional',
        'dirty south rap': 'Miscellaneous',
        'eau claire indie': 'Pop & Indie',
        'ohio hip hop': 'Miscellaneous',
        'ottawa indie': 'Pop & Indie',
        'motown': 'Miscellaneous',
        'country pop': 'Folk & Country',
        'classic texas country': 'Folk & Country',
        'modern southern rock': 'Rock & Metal',
        'roots rock': 'Rock & Metal',
        'western americana': 'Folk & Country',
        'chill abstract hip hop': 'Miscellaneous',
        'country': 'Folk & Country',
        'country dawn': 'Folk & Country',
        'new england americana': 'Folk & Country',
        'rva indie': 'Pop & Indie',
        'latin pop': 'World & Regional',
        'hawaiian hip hop': 'World & Regional',
        'cologne indie': 'Pop & Indie',
        'german singer-songwriter': 'World & Regional',
        'acoustic pop': 'Pop & Indie',
        'ectofolk': 'Folk & Country',
        'wrestling': 'Miscellaneous',
        'stomp and flutter': 'Miscellaneous',
        'teen pop': 'Pop & Indie',
        'british singer-songwriter': 'Pop & Indie',
        'arkansas country': 'Folk & Country',
        'talent show': 'Miscellaneous',
        'electronicore': 'Electronic & Dance',
        'post-post-hardcore': 'Rock & Metal',
        'south dakota indie': 'Pop & Indie',
        'orebro indie': 'Pop & Indie',
        'pop quebecois': 'Pop & Indie',
        'boston hip hop': 'Miscellaneous',
        'britpop revival': 'Pop & Indie',
        'liverpool indie': 'Pop & Indie',
        'vapor pop': 'Pop & Indie',
        'sheffield indie': 'Pop & Indie',
        'girl group': 'Pop & Indie',
        'leeds indie': 'Pop & Indie',
        'north carolina emo': 'Pop & Indie',
        'seattle indie': 'Pop & Indie',
        'grand rapids indie': 'Pop & Indie',
        'jacksonville indie': 'Pop & Indie',
        'austin rock': 'Rock & Metal',
        'austindie': 'Pop & Indie',
        'south african rock': 'World & Regional',
        'aesthetic rap': 'Miscellaneous',
        'bossbeat': 'Miscellaneous',
        'scandipop': 'World & Regional',
        'swedish post-hardcore': 'Rock & Metal',
        'rhode island indie': 'Pop & Indie',
        'dayton indie': 'Pop & Indie',
        'sophisti-pop': 'Pop & Indie',
        'windsor on indie': 'Pop & Indie',
        'ann arbor indie': 'Pop & Indie',
        'early us punk': 'Rock & Metal',
        'lexington ky indie': 'Pop & Indie',
        'san diego indie': 'Pop & Indie',
        'surf punk': 'Rock & Metal',
        'chiptune': 'Electronic & Dance',
        'christian metal': 'Rock & Metal',
        'christian metalcore': 'Rock & Metal',
        'memphis hip hop': 'Miscellaneous',
        'tennessee hip hop': 'Miscellaneous',
        'kansas city hip hop': 'Miscellaneous',
        'north carolina hip hop': 'Miscellaneous',
        'rebel blues': 'Jazz & Blues',
        'alabama indie': 'Pop & Indie',
        'womens music': 'Miscellaneous',
        'basshall': 'Electronic & Dance',
        'atlanta metal': 'Rock & Metal',
        'deathcore': 'Rock & Metal',
        'houston indie': 'Pop & Indie',
        'classic country pop': 'Folk & Country',
        'blues rock': 'Rock & Metal',
        'detroit rock': 'Rock & Metal',
        'chicago hardcore': 'Rock & Metal',
        'chicago punk': 'Rock & Metal',
        'protopunk': 'Rock & Metal',    
    }

    # Save mapping to json
    with open('genre_mapping.json', 'w') as f:
        json.dump(genre_to_category, f, indent=2)

def main():
    chunk_missing_genres()
    create_mapping()

if __name__ == '__main__':
    main()